FROM cockroachdb/cockroach:v23.1.6

LABEL org.opencontainers.image.source=https://github.com/withGetAPet/ci
LABEL org.opencontainers.image.description="Cockroach for GetAPet"

CMD [ "start-single-node", "--insecure" ]