name: Docker Build
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.*
      - .github/workflows/docker.yml

jobs:
  build:
    name: Build
    # We need to make sure both the Dockerfile and the branch is main
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: build
            file: Dockerfile.build
          - name: migrator
            file: Dockerfile.migrator
          - name: cockroach
            file: Dockerfile.cockroach

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/withgetapet/${{ matrix.name }}:${{ github.sha }}
            ghcr.io/withgetapet/${{ matrix.name }}:latest